name: Bug report
description: Report an issue that needs to be fixed
title: 'Bug: '
type: Bug
labels: ['bug']
projects: ['Borodevia/1']
body:
  - type: dropdown
    attributes:
      label: Module
      description: Select the module where the bug was found.
      multiple: true
      options:
        - eDziennik Dashboard
        - eDziennik Schedule
        - eDziennik GradeBook
        - eDziennik Mail
        - eDziennik Council
  - type: dropdown
    attributes:
      label: User Role
      description: Select your role in the system.
      options:
        - Student
        - Teacher
        - Parent
        - Administrator
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |-
        Describe the bug in detail.
        What happened? What do you see?
        If possible, include screenshots
      placeholder: A clear description and screenshots of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |-
        Provide a step-by-step description of how to reproduce the bug.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: A clear set of steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |-
        Describe what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
  - type: dropdown
    attributes:
      label: Browser
      description: Select the browser where you encountered the bug.
      options:
        - Chrome (or other chromium-based, e.g. Brave)
        - Edge (or Internet Explorer)
        - Firefox (or other Gecko-based, e.g. Tor, Zen)
        - Opera (or similiar, e.g. Opera GX)
        - Safari
        - Chrome Android (or other chromium-based on Android, e.g. Brave Android)
        - Firefox for Android (or other Gecko-based on Android, e.g. Tor)
        - Opera Android (or similiar on Android, e.g. Opera Lite for Android)
        - Safari for iOS
        - Samsung Internet
        - Other
      default: 10
    validations:
      required: true
  - type: input
    attributes:
      label: Browser Version
      description: |-
        Provide the full version of the browser where you encountered the bug.
        To find the version, check the "About" section in your browser's settings
        or go to (about:version)[about:version]
      placeholder: e.g. 142.0.3595.94
    validations:
      required: true
  - type: input
    attributes:
      label: User-Agent
      description: |-
        Provide the full User-Agent string of your browser.
        You can find it at (about:version)[about:version]
      placeholder: e.g. Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Browser extensions
      description: |-
        List any browser extensions you have installed that might affect the behavior of the website.
      placeholder: e.g. uBlock Origin, Privacy Badger, etc.
  - type: input
    attributes:
      label: whatsmybrowser.org link
      description: |-
        Provide a link to your browser details from [whatsmybrowser.org](https://www.whatsmybrowser.org/).
        This helps to quickly gather all necessary information about your browser.
      placeholder: e.g. https://www.whatsmybrowser.org/b/XXXXXX
