import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { IntlProvider } from 'next-intl';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = require('../messages/en.json');

  return (
    <html lang="en">
      <head />
      <body>
        <IntlProvider locale="en" messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </IntlProvider>
      </body>
    </html>
  );
}
